"use client"

import { useRef } from "react"
import { TrendingUp, TrendingDown, Check, AlertTriangle, Clock, HeartHandshake, HeartPulse } from "lucide-react"
import html2canvas from "html2canvas"
import { useAnalysis } from "@/components/analysis-context"

export function SampleReport() {
  const { result, isLoading, error } = useAnalysis()

  const hasResult = !!result

  const likeLikelihoodValue = hasResult ? Math.min(100, Math.max(0, result!.likeLikelihood)) : 72
  const chemistryScoreValue = hasResult ? Math.min(100, Math.max(0, result!.score)) : 78

  const rawFlirtScore =
    hasResult && typeof result?.flirtScore === "number" && Number.isFinite(result.flirtScore)
      ? result.flirtScore
      : null
  const flirtScoreValue = rawFlirtScore !== null ? Math.min(100, Math.max(0, rawFlirtScore)) : null

  const scoreText = hasResult ? result!.scoreText || "Moderate chemistry detected" : "Strong mutual connection detected"
  const likeStatus = hasResult ? result!.likeStatus || "Probably Interested" : "Probably Interested"
  const flirtStatus = hasResult ? result!.flirtStatus || "Mixed but playful" : "Mixed but playful"

  const hasRedFlags = hasResult && result!.redFlagIndex !== "Low"

  const shareCardRef = useRef<HTMLDivElement | null>(null)

  async function handleShare() {
    if (!shareCardRef.current) return

    try {
      const canvas = await html2canvas(shareCardRef.current, {
        backgroundColor: "#020617",
        scale: 2,
      })
      const dataUrl = canvas.toDataURL("image/png")

      const link = document.createElement("a")
      link.href = dataUrl
      link.download = "chemdecode-report.png"
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
    } catch (e) {
      console.error("Failed to generate share image", e)
    }
  }

  return (
    <section id="sample" className="relative px-4 py-16 sm:px-6 sm:py-24">
      <div className="mx-auto max-w-5xl">
        {/* Hidden share card for snapshot */}
        <div
          ref={shareCardRef}
          className="pointer-events-none fixed left-[-9999px] top-0 z-[-1] h-auto w-[900px] select-none rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-emerald-900 p-10 text-slate-50 shadow-2xl"
        >
          <div className="mb-8 flex items-center justify-between">
            <div>
              <p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-400">
                ChemDecode
              </p>
              <h2 className="mt-2 text-3xl font-semibold tracking-tight text-slate-50">
                Relationship Chemistry Snapshot
              </h2>
            </div>
          </div>

          <div className="grid gap-10 md:grid-cols-[1.1fr,0.9fr]">
            <div className="space-y-6">
              <div>
                <p className="mb-3 text-xs font-medium uppercase tracking-[0.2em] text-emerald-300">
                  Overall Chemistry
                </p>
                <p className="text-6xl font-semibold text-emerald-400">
                  {hasResult ? `${Math.round(chemistryScoreValue)}%` : "78%"}
                </p>
                <p className="mt-3 max-w-md text-sm leading-relaxed text-slate-200">
                  {scoreText}
                </p>
              </div>
            </div>

            <div className="space-y-6">
              <div>
                <p className="mb-3 text-xs font-medium uppercase tracking-[0.2em] text-emerald-300">
                  Likelihood They Like You
                </p>
                <p className="text-2xl font-semibold text-slate-50">
                  {hasResult ? `${Math.round(likeLikelihoodValue)}%` : "72%"}
                </p>
                <p className="mt-2 text-lg font-semibold text-emerald-300">
                  {likeStatus}
                </p>
              </div>

              <div className="mt-8 rounded-2xl border border-emerald-500/40 bg-black/20 px-5 py-4 text-xs leading-relaxed text-slate-300">
                This snapshot is a brutally honest vibe check of your chat energy, not a life sentence. Use it as a
                mirror, then decide what you want to do next.
              </div>
            </div>
          </div>

          <div className="mt-10 flex items-center justify-between border-t border-white/10 pt-4 text-xs text-slate-400">
            <span>Generated by ChemDecode</span>
            <span className="font-medium text-emerald-300">chemdecode.com</span>
          </div>
        </div>

        <div className="mb-12 text-center">
          <p className="mb-3 text-sm font-medium tracking-wider text-accent uppercase">
            {hasResult ? "Your Report" : "Sample Report"}
          </p>
          <h2 className="mb-4 text-3xl font-bold tracking-tight md:text-4xl">
            {hasResult ? "Here’s Your Chemistry Read" : "See What You&apos;ll Discover"}
          </h2>
          <p className="mx-auto max-w-2xl text-muted-foreground">
            {hasResult
              ? "We’ve decoded your screenshots and translated them into a brutally honest chemistry breakdown."
              : "Here&apos;s a preview of the detailed analysis you&apos;ll receive after uploading your screenshots."}
          </p>
        </div>

        <div className="overflow-hidden rounded-xl border border-border/50 bg-card/50 shadow-xl sm:rounded-2xl">
          {/* Report Header */}
          <div className="border-b border-border/50 bg-secondary/30 px-4 py-3 sm:px-6 sm:py-4 md:px-8">
            <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <h3 className="text-sm font-semibold sm:text-base">
                  {hasResult ? "Relationship Chemistry Report" : "Relationship Analysis Report"}
                </h3>
                <p className="text-xs text-muted-foreground sm:text-sm">
                  {hasResult
                    ? "Based on your uploaded screenshots"
                    : "Conversation with Alex • 47 messages analyzed"}
                </p>
              </div>
              <div className="flex items-center gap-2">
                <div className="flex items-center gap-2 rounded-full bg-accent/10 px-2 py-1 sm:px-3">
                  <Clock className="h-3 w-3 text-accent" />
                  <span className="text-xs text-accent">
                    {isLoading ? "Decoding your relationship chemistry..." : "Generated just now"}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Final Verdict Card (Layer 1) */}
          <div className="border-b border-border/50 bg-secondary/40 px-4 py-5 sm:px-6 sm:py-6 md:px-8">
            <div className="flex items-start gap-3 rounded-xl bg-background/60 p-4 shadow-inner sm:p-5">
              <div className="mt-0.5 rounded-lg bg-accent/15 p-2">
                <HeartHandshake className="h-5 w-5 text-accent" />
              </div>
              <div>
                <p className="mb-2 text-xs font-medium uppercase tracking-[0.16em] text-accent sm:text-[11px]">
                  Final Verdict
                </p>
                <p className="text-base font-semibold leading-relaxed text-foreground sm:text-xl">
                  {hasResult
                    ? result!.verdict || "No clear verdict. Not enough consistent evidence."
                    : "You’re looking at a connection with solid potential if both of you keep showing up with this level of energy."}
                </p>
              </div>
            </div>

            <div className="mt-5 flex flex-col items-start gap-2 sm:flex-row sm:items-center sm:justify-between">
              <button
                type="button"
                onClick={handleShare}
                className="inline-flex items-center justify-center rounded-full bg-emerald-600 px-5 py-2.5 text-sm font-semibold text-white shadow-lg transition-transform duration-150 hover:scale-105 hover:bg-emerald-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950"
              >
                Share my result
              </button>
              <p className="max-w-md text-xs leading-relaxed text-muted-foreground sm:text-sm">
                Send this to your friend and ask if they agree with the AI.
              </p>
            </div>
          </div>

          {/* Main Metrics – Layer 1 core summary */}
          <div className="grid gap-4 border-b border-border/50 bg-gradient-to-br from-background via-background to-secondary/20 p-4 sm:grid-cols-3 sm:p-6 md:p-8">
            {/* Overall Chemistry */}
            <div className="rounded-xl border border-border/60 bg-secondary/40 p-4">
              <div className="mb-1 text-xs text-muted-foreground sm:mb-2 sm:text-sm">Overall Chemistry</div>
              <div className="mb-1 flex items-baseline gap-1 sm:gap-2">
                <span className="text-4xl font-bold text-accent sm:text-5xl md:text-6xl">
                  {hasResult ? `${Math.round(chemistryScoreValue)}%` : "78%"}
                </span>
                <TrendingUp className="h-3 w-3 text-green-400 sm:h-4 sm:w-4" />
              </div>
              <p className="mt-1 text-sm text-muted-foreground sm:text-base md:text-lg">
                {scoreText}
              </p>
              <p className="mt-2 text-[11px] text-muted-foreground/80 sm:text-xs">
                Overall connection
              </p>
            </div>

            {/* Likelihood They Like You */}
            <div className="rounded-xl border border-border/60 bg-secondary/40 p-4">
              <div className="mb-1 flex items-center justify-between text-xs sm:text-sm">
                <span className="text-muted-foreground">Likelihood They Like You</span>
                <span className="text-sm font-semibold text-foreground sm:text-base">
                  {hasResult ? `${Math.round(likeLikelihoodValue)}%` : "72%"}
                </span>
              </div>
              <div className="mb-2 h-2 overflow-hidden rounded-full bg-secondary">
                <div
                  className="h-full rounded-full bg-accent"
                  style={{ width: `${likeLikelihoodValue || 0}%` }}
                />
              </div>
              <p className="text-sm font-semibold text-accent sm:text-base md:text-lg">
                {likeStatus}
              </p>
              <p className="mt-2 text-[11px] text-muted-foreground/80 sm:text-xs">
                Romantic interest
              </p>
            </div>

            {/* Flirt Score */}
            <div className="rounded-xl border border-border/60 bg-secondary/40 p-4">
              <div className="mb-1 flex items-center justify-between text-xs sm:mb-2 sm:text-sm">
                <span className="text-muted-foreground">Flirt Score</span>
              </div>
              <div className="mb-1 flex items-baseline gap-2">
                <span className="text-4xl font-bold text-accent sm:text-5xl md:text-6xl">
                  {hasResult
                    ? flirtScoreValue !== null
                      ? `${Math.round(flirtScoreValue)}%`
                      : "--"
                    : "64%"}
                </span>
                <HeartPulse className="h-4 w-4 text-accent" />
              </div>
              <p className="text-sm font-semibold text-accent sm:text-base md:text-lg">
                {flirtStatus}
              </p>
              <p className="mt-2 text-[11px] text-muted-foreground/80 sm:text-xs">
                Playful / teasing / romantic energy
              </p>
            </div>
          </div>

          {/* Detailed Analysis – Layer 2 */}
          <div className="grid gap-4 p-4 sm:gap-6 sm:p-6 md:grid-cols-[1.1fr,0.9fr] md:p-8">
            {/* Conversation Signals & Red Flags */}
            <div className="space-y-4">
              {/* Interest Balance / Who Cares More */}
              <div className="mb-4 rounded-xl border border-border/60 bg-secondary/40 p-4 sm:p-5">
                <div className="mb-1 text-xs text-muted-foreground sm:mb-2 sm:text-sm">Who Cares More</div>
                <div className="mb-1 flex items-center gap-2 sm:gap-3">
                  <HeartHandshake className="h-4 w-4 text-accent" />
                  <span className="text-base font-semibold sm:text-lg md:text-xl">
                    {hasResult ? result!.whoCaresMore : "Roughly balanced"}
                  </span>
                </div>
                <p className="mt-1 text-sm leading-relaxed text-muted-foreground sm:text-base">
                  {hasResult
                    ? "Decoded from who initiates, who follows up emotionally, and who keeps the conversation alive."
                    : "Shows who is subtly carrying more of the emotional and conversational weight."}
                </p>
              </div>

              {/* Conversation Signals */}
              <div className="rounded-xl border border-border/50 bg-secondary/30 p-4 sm:p-5">
                <div className="mb-4 mt-4 flex items-center justify-between sm:mt-6">
                  <h4 className="text-xl font-semibold sm:text-2xl">Conversation Signals</h4>
                </div>
                <div className="space-y-3">
                  {isLoading && (
                    <p className="text-base leading-relaxed text-muted-foreground sm:text-lg">
                      We&apos;re decoding your relationship chemistry. This will only take a moment.
                    </p>
                  )}

                  {!isLoading && hasResult && result!.signals.length > 0 && (
                    <ul className="space-y-3">
                      {result!.signals.map((signal, index) => {
                        const text = signal.toString()
                        const trimmed = text.trim()
                        const firstChar = trimmed[0]
                        const isPositive = firstChar === "✓"
                        const isWarning = firstChar === "⚠" || firstChar === "!"

                        const displayText = isPositive || isWarning ? trimmed.slice(1).trim() : trimmed

                        return (
                          <li
                            key={index}
                            className="flex items-start gap-3 rounded-lg bg-background/40 px-3 py-2 text-base sm:text-lg"
                          >
                            {isPositive && (
                              <Check className="mt-0.5 h-4 w-4 shrink-0 text-green-400" />
                            )}
                            {isWarning && (
                              <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-yellow-400" />
                            )}
                            {!isPositive && !isWarning && (
                              <span className="mt-0.5 inline-block h-1.5 w-1.5 rounded-full bg-muted-foreground/70" />
                            )}
                            <p
                              className={`leading-relaxed ${
                                isPositive
                                  ? "text-emerald-100"
                                  : isWarning
                                    ? "text-yellow-100"
                                    : "text-muted-foreground"
                              }`}
                            >
                              {displayText}
                            </p>
                          </li>
                        )
                      })}
                    </ul>
                  )}

                  {!isLoading && !hasResult && (
                    <p className="text-base leading-relaxed text-muted-foreground sm:text-lg">
                      We&apos;ll break down concrete patterns like reply time, message length, and who actually drives the
                      conversation.
                    </p>
                  )}

                  {!isLoading && hasResult && result!.signals.length === 0 && (
                    <p className="text-base leading-relaxed text-muted-foreground sm:text-lg">
                      No specific conversation signals were extracted, but the overall chemistry score still gives a decent read.
                    </p>
                  )}
                </div>
              </div>

              {/* Red Flags Block – only when not Low */}
              {hasRedFlags && (
                <div className="rounded-xl border border-amber-500/60 bg-amber-950/40 p-4 sm:p-5">
                  <div className="mb-3 flex items-center gap-2">
                    <AlertTriangle className="h-4 w-4 text-amber-400" />
                    <h4 className="text-xl font-semibold text-amber-100 sm:text-2xl">
                      Red Flags Detected ({result!.redFlagIndex})
                    </h4>
                  </div>
                  <p className="mb-3 text-sm leading-relaxed text-amber-100/80 sm:text-base">
                    These are the specific behaviors that are driving the red-flag rating:
                  </p>
                  <ul className="space-y-2">
                    {result!.flagSignals.map((flag, index) => (
                      <li key={index} className="flex items-start gap-3 text-base leading-relaxed text-amber-50 sm:text-lg">
                        <span className="mt-[5px] inline-block h-1.5 w-1.5 rounded-full bg-amber-400" />
                        <span>{flag}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>

            {/* Key Insights */}
            <div className="space-y-4">
              <div className="rounded-xl border border-border/50 bg-secondary/30 p-4 sm:p-5">
                <h4 className="mb-4 mt-4 text-xl font-semibold sm:mt-6 sm:text-2xl">Key Insights</h4>
                <div className="space-y-3">
                  {isLoading && (
                    <p className="text-base leading-relaxed text-muted-foreground sm:text-lg">
                      We&apos;re decoding your relationship chemistry. This will only take a moment.
                    </p>
                  )}

                  {!isLoading && hasResult && result!.insights.length > 0 && (
                    <>
                      {result!.insights.map((insight, index) => {
                        const text = insight.toString().trim()
                        const [firstSentence, ...restSentences] = text.split(/(?<=[.!?])\s+/)
                        const detail = restSentences.join(" ")

                        return (
                          <div
                            key={index}
                            className="flex items-start gap-3 rounded-lg bg-background/40 px-3 py-3"
                          >
                            <Check className="mt-0.5 h-4 w-4 shrink-0 text-green-400" />
                            <div className="space-y-1">
                              <p className="text-base font-semibold leading-relaxed text-foreground sm:text-lg">
                                {firstSentence}
                              </p>
                              {detail && (
                                <p className="text-sm leading-relaxed text-muted-foreground sm:text-base">
                                  {detail}
                                </p>
                              )}
                            </div>
                          </div>
                        )
                      })}
                    </>
                  )}

                  {!isLoading && !hasResult && (
                    <>
                      <div className="flex items-start gap-3">
                        <Check className="mt-0.5 h-4 w-4 shrink-0 text-green-400" />
                        <p className="text-base leading-relaxed text-muted-foreground sm:text-lg">
                          Quick response times and curious follow-up questions usually signal genuine interest.
                        </p>
                      </div>
                      <div className="flex items-start gap-3">
                        <Check className="mt-0.5 h-4 w-4 shrink-0 text-green-400" />
                        <p className="text-base leading-relaxed text-muted-foreground sm:text-lg">
                          Consistent emotional tone matters more than the occasional overthinking reply.
                        </p>
                      </div>
                    </>
                  )}

                  {!isLoading && hasResult && result!.insights.length === 0 && (
                    <p className="text-base leading-relaxed text-muted-foreground sm:text-lg">
                      We couldn&apos;t extract specific insights, but the chemistry and likelihood scores still tell a story.
                    </p>
                  )}

                  {error && !isLoading && (
                    <p className="text-base leading-relaxed text-red-400 sm:text-lg">
                      {error}
                    </p>
                  )}
                </div>
              </div>

              {/* Tiny footer note */}
              <div className="rounded-xl border border-border/40 bg-secondary/20 px-4 py-3 text-xs text-muted-foreground">
                This analysis is a brutally honest vibe check, not therapy. Use it as a mirror, not a sentence.
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

